version: "3.9"

networks:
  itam_net:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    container_name: itam_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: itamdb
      MYSQL_USER: itamuser
      MYSQL_PASSWORD: itam@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - itam_net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: itam_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: itamuser
      DB_PASSWORD: itam@123
      DB_NAME: itamdb
      JWT_SECRET: SUPERSECRETJWTKEY
    depends_on:
      - mysql
    networks:
      - itam_net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: itam_frontend
    ports:
      - "3000:3000"
    networks:
      - itam_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: itam_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - itam_net

  nginx:
    image: nginx:latest
    container_name: itam_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - itam_net

volumes:
  mysql_data:

